### ISSUE TITLE
limit 1000 words

### ISSUE THREAD

**Issue by andrewufrank** [dkmfbk/pikes#6]
i have downloaded and installed on a debian stretch box with java 1.8.0_121. installations following your instructions was very easy  - thank you! i start the server with 8GB. 
when i access the server in a browser window i get `Input too long (1329 chars, limit is 1000)`. what is necessary to process longer paragraphs?  what are I doing wrong? 
thank you for help!

**Comment by ziorufus** [comment]
PIKES is limited by default to 1000 chars. If you want to increase this limit, just create a properties file (i.e. `config.properties`) with this line

```
max_text_len=100000
```

Then restart PIKES with the `-c` option.

```
java -Xmx8G eu.fbk.dkm.pikes.tintop.server.PipelineServer -c config.properties
```

**Comment by andrewufrank** [comment]
thank you - it worked (and i found that the information was on the PIKES page - i just did not register with me).
